### ISSUE TITLE
翻页按钮遮挡目录

### ISSUE THREAD

**Issue by Winson-Huang** [baddate/trilium-wiki#1]
如图：

![图片](https://github.com/baddate/trilium-wiki/assets/47921347/a04b3644-1b27-4857-acc5-d59478cd518d)

“上一页”按钮会遮挡目录。

**Comment by baddate** [comment]
Thanks for feedback, it has been fixed now.
check it here: https://trilium.smj.im

**Comment by Winson-Huang** [comment]
ok
